services:
  - type: web
    name: aooni
    runtime: static
    buildCommand: echo "No build required"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
